version: '3.9'

name: flights-block4

services:
  nodejs-api:
    container_name: flight-status-api
    build: .
    ports:
      - '8888:8888'
    depends_on:
      - db
      - consul
    environment:
      - NODE_ENV=prod
  db:
    container_name: flight-status-db
    image: mongo:5.0.14
    ports:
      - '27018:27017'
    volumes:
      - ./docker/data/mongo/db:/data/db
  consul:
    container_name: flight-status-consul
    image: consul:1.15.2
    ports:
      - '8501:8500'
    volumes:
      - ./docker/data/consul/data:/consul/data
      - ./docker/data/consul/config:/consul/config
      - ./resources/consul:/resources/consul
    command:
      - sh
      - -c
      - |
        consul agent -server -ui -bind 0.0.0.0 -client 0.0.0.0 -data-dir /consul/data -config-dir /consul/config -bootstrap -datacenter docker &
        consul_pid=$!
        sleep 5
        consul kv import -http-addr=http://0.0.0.0:8500 @/resources/consul/consul-config-kv.json
        wait $consul_pid

networks:
  default:
    name: flights-block5_1_external
    external: true
